### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by AlexandreAdam** [aymgal/COOLEST#36]
Please include a small statement in the `README.md` file for the installation method, either with `pip` or directly calling the `setup.py` script. There should be a method to install the package for general usage and one for development / testing.

**Comment by aymgal** [comment]
This [commit](https://github.com/aymgal/COOLEST/commit/7de034a523ce974b964d1536cc57fcdb4631f6a4) should have fixed this issue, by adding installation instructions using pip together with the `setup.py`. Let me know if anything else is still missing.

**Comment by AlexandreAdam** [comment]
Awsome!
