### ISSUE TITLE
List of conventions

### ISSUE THREAD

**Issue by AlexandreAdam** [aymgal/COOLEST#37]
Please provide the full list of convention in the README.md file, similar to what is done in the documentation.

**Comment by aymgal** [comment]
This [commit](https://github.com/aymgal/COOLEST/commit/7de034a523ce974b964d1536cc57fcdb4631f6a4) should have fixed this issue, by adding a link to the conventions markdown file (which is the one used in the documentation).

**Comment by AlexandreAdam** [comment]
Thanks!
