### ISSUE TITLE
Hosting the documentation

### ISSUE THREAD

**Issue by AlexandreAdam** [aymgal/COOLEST#38]
While individual classes have a neat documentation, I would find it useful to have a dedicated website hosting the documentation. The docs and html for this are already in the joss branch, but I could not find the documentation online. Please provide a link to it in the `README.md` file when it is properly hosted.

**Comment by aymgal** [comment]
This [commit](https://github.com/aymgal/COOLEST/commit/7de034a523ce974b964d1536cc57fcdb4631f6a4) should have fixed this issue, by adding a link to the documentation hosted on readthedocs.

**Comment by AlexandreAdam** [comment]
Awsome thanks!
