### ISSUE TITLE
Examples in the documentation

### ISSUE THREAD

**Issue by AlexandreAdam** [aymgal/COOLEST#39]
Please provide a notebook showcasing the plotting API. A notebook detailing how to reproduce the main figure of the paper should be sufficient.

**Comment by aymgal** [comment]
There was actually the notebook that generated the paper figure in the `joss` directory. I moved it to the same directory as the other notebooks, [`docs/notebooks`](https://github.com/aymgal/COOLEST/tree/joss/docs/notebooks), which are then rendered in the [online doc](https://coolest.readthedocs.io/en/latest/index.html).

**Comment by AlexandreAdam** [comment]
Yep, my bad I found them. All look fine to me thanks!
