### ISSUE TITLE
Uninformative message

### ISSUE THREAD

**Issue by gvernard** [aymgal/COOLEST#48]
Can we get rid of the following message that appears when loading a coolest file? It is alarming to see 'Failed reading...' even though the operation was successful. Is isn't so important to report about missing (and not necessary) _pyAPI files anyway.

Failed reading '_pyAPI' template with jsonpickle, now trying with the pure json template (original error: Template file at '<some_path>/coolest_vkl_pyAPI.json' does not exist.)

**Comment by aymgal** [comment]
@gvernard you can already set `verbose=False` to get read of the message. But indeed, probably in the future the `jsonpickle` will be dropped anyway...
