### ISSUE TITLE
More mass models

### ISSUE THREAD

**Issue by gvernard** [aymgal/COOLEST#54]
We should try and add more mass models, e.g. the ones that appear in Nightingale et al. (2022) - "Scanning for DM subhalos..."

**Comment by aymgal** [comment]
Yes that would be useful. In order not to re-implement a lot of profiles already existing and well-tested in other lensing codes (other than the standard ones than power-law and external shear, Sérsic, etc.), we should use a "backend" lensing code depending on the mass profile needed. This is what is done for the [shapelets light profile](https://github.com/aymgal/COOLEST/blob/80c61c585c4fdff03b26577e17513eaa3120fc54/coolest/api/profiles/light.py#L74) in the API, which uses lenstronomy in the background.

I am not familiar with the PyAutoLens, so I don't know how easy it is to call PyAutoLens functions from the coolest API interface.
