### ISSUE TITLE
PyPI submission

### ISSUE THREAD

**Issue by musoke** [aymgal/COOLEST#58]
Would you be open to publishing this package on [PyPI](https://pypi.org/)?

This would eliminate the need to manually clone this repository and install the package, especially when it is used as a dependency in other packages.  pip would be able to find and install it automatically.

**Comment by aymgal** [comment]
Hi @musoke , thanks for opening this issue. It would be better to have a PyPi, it was actually planned. Unfortunately I can work on this only in a couple of weeks. Did you manage to install it via the repo? Let me know if you have any problem.

**Comment by musoke** [comment]
Yup, installing was easy once I found this repo. So I guess discoverability
would be another advantage of uploading to PyPI.

In any case, I'm all sorted now.  I just opened this issue to simplify
things for others in the future.

**Comment by aymgal** [comment]
@musoke PR #64 and subsequent commits have made the package available through PyPI. Hence I close the issue, thanks!

**Comment by musoke** [comment]
😄
