### ISSUE TITLE
support for negative convergence in convergence sheet.

### ISSUE THREAD

**Issue by nkhadka21** [aymgal/COOLEST#62]
Hi @aymgal, currently, coolest does not allow negative convergence values in the convergence sheet. I believe that allowing negative convergence values is important to ensure that the average convergence across the universe is zero during sampling. Therefore, it would be beneficial to have the capability to use negative kappa values in coolest. Thank you!

**Comment by aymgal** [comment]
@nkhadka21 You're absolutely right, thanks for pointing this out! I merged PR #63 to the main branch, which should fix the issue. But please re-open if this is not the case!
